classDiagram
  class src {
  }
  class database {
  }
  class db_manager {
  }
  class main {
  }
  class models {
  }
  class playlist {
  }
  class track {
  }
  main --> db_manager
  main --> playlist
  main --> track
